---
- hosts: web01
  become: yes
  tasks: 
        - name: install apache2 on client
          apt: name=apache2 state=present
        - name: service start
          service: name=apache2 enabled=no
...
